### ISSUE TITLE
Device

### ISSUE THREAD

**Issue by leofrederiche** [lleonardoll/raddit#1]
Device é para o cadastro de usuário  e login né? Nesse caso posso usar o bcrypt ao invés do Device?

**Comment by jmscarpa** [comment]
Leonardo, isso mesmo. O deviSe (com s ) é para login e controle de
usuário.  Ele faz mais um monte de coisa. Da uma olhadinha n pagina dele no
github

**Comment by michelamaral** [comment]
Leonardo,
Use o devise... é um requisito da tarefa. ;)
O objetivo é aprender a usar o devise.

Em Wed Feb 04 2015 at 1:40:26 PM, João Mateus Scarpa <
notifications@github.com> escreveu:

> Leonardo, isso mesmo. O deviSe (com s ) é para login e controle de
> usuário. Ele faz mais um monte de coisa. Da uma olhadinha n pagina dele no
> github
> 
> On Wed, Feb 4, 2015, 1:16 PM Leonardo Camp Frederiche <

**Comment by leofrederiche** [comment]
ok bora saber mais o/
