### ISSUE TITLE
Custom validate

### ISSUE THREAD

**Issue by leofrederiche** [lleonardoll/raddit#2]
Não estou conseguindo fazer a validação customizada, acredito que seja algo no model LINK
![screenshot from 2015-02-07 00 49 53](https://cloud.githubusercontent.com/assets/6271955/6090518/53a80048-ae63-11e4-9059-83032a2fd150.png)
![screenshot from 2015-02-07 00 50 05](https://cloud.githubusercontent.com/assets/6271955/6090519/53ab81c8-ae63-11e4-89bb-09cc759fdced.png)

**Comment by jmscarpa** [comment]
Qual o erro? Posta a mensagem aqyi

**Comment by leofrederiche** [comment]
Então acho que o código ai tava errado, agora ta assim: 
![screenshot from 2015-02-07 11 22 25](https://cloud.githubusercontent.com/assets/6271955/6092217/a35ec10a-aebb-11e4-945a-59172f4ab06e.png)
![screenshot from 2015-02-07 11 22 31](https://cloud.githubusercontent.com/assets/6271955/6092218/a365a4b6-aebb-11e4-94a5-06c6c834d06a.png)

O erro que está dando é uninitialized constant Link::UrlValidator
Já configurei o application.rb para ele ler o arquivo url_validator.rb

**Comment by michelamaral** [comment]
Manda o Print do erro

**Comment by leofrederiche** [comment]
![screenshot from 2015-02-07 12 19 58](https://cloud.githubusercontent.com/assets/6271955/6092390/af671e18-aec3-11e4-8e94-eae854eb489b.png)

**Comment by jmscarpa** [comment]
Tenta trocar o nome da sua classe para Link::UrlValidator

**Comment by leofrederiche** [comment]
Não mudou nada, teria que mudar o nome do arquivo também?

**Comment by leofrederiche** [comment]
Opa concegui, mais ficou tudo dentro do model Link, tem algum problema? 

``` ruby
class Link < ActiveRecord::Base

  validates_presence_of :url, :title
  validate :validate

  def validate
    record = url
    unless record.starts_with? "http://" 
      errors.add(:url, "Insira um link valido.")
    end
  end

end
```

**Comment by jmscarpa** [comment]
Só arruma esse nome dele ai. Def validate nao ficou bom. Pode explicar o
que ele faz mesmo. (Validate link format)
