### ISSUE TITLE
Nem sempre dá para clicar nas imagens de "up" e "down"

### ISSUE THREAD

**Issue by michelamaral** [lleonardoll/raddit#4]
![link](https://cloud.githubusercontent.com/assets/379973/6160593/28f93636-b24c-11e4-888c-3c9a21dd8b44.png)

**Comment by leofrederiche** [comment]
Acredito que seja o invert do CSS, já estou vendo tudo ;)

**Comment by leofrederiche** [comment]
Corrigido, o link ficava a baixo da imagem.
