### ISSUE TITLE
Está salvando com url incompleta

### ISSUE THREAD

**Issue by michelamaral** [lleonardoll/raddit#6]
Se colocar só http:// está deixando salvar. Não deveria.
Talvez a gem 'validate_url' resolva. Veja aqui: https://rubygems.org/gems/validate_url

![validate-url](https://cloud.githubusercontent.com/assets/379973/6160686/8b389d04-b24d-11e4-95d9-4d34283209e0.png)

**Comment by leofrederiche** [comment]
Neste caso pra validar toda a url seria verificando se no final existe .com/.br/.net etc?

**Comment by leofrederiche** [comment]
Corrigido ;)
