### ISSUE TITLE
Está salvando comentário em branco

### ISSUE THREAD

**Issue by michelamaral** [lleonardoll/raddit#7]
Está salvando sem comentário.

É muito importante em todo cadastro definir os campos que são obrigatórios e também dar uma mensagem para o usuário se ele não preencher estes campos.

Veja:

![empty-comments](https://cloud.githubusercontent.com/assets/379973/6160723/1d2b369a-b24e-11e4-878b-748d6d77f8d5.png)

**Comment by leofrederiche** [comment]
Opa já vou corrigir ;)
